name: CI

on: 
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i
      - run: CI=false npm run build
      - run: ls -la
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/lightsail.key
          chmod 600 ~/.ssh/lightsail.key
          cat >>~/.ssh/config <<END
          Host lightsail
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/lightsail.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.KEY }}
          SSH_HOST: ${{ secrets.HOST }}
      - name: Deploy to lightsail
        run: scp -r build lightsail:/var/www/html
