name: CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ steps.extract_branch.outputs.branch }}
      - name: Clone git
        run: git clone https://github.com/hdduy97/cicd.git
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/lightsail.key
          chmod 600 ~/.ssh/lightsail.key
          cat >>~/.ssh/config <<END
          Host lightsail
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/lightsail.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.KEY }}
          SSH_HOST: ${{ secrets.HOST }}
      - name: Deploy to lightsail
        run: |
          rm -r cicd/.github
          scp -r cicd/* lightsail:/var/www/html
